# Generated by Django 4.1.2 on 2022-10-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artiste',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='artiste',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='artiste',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='lyric',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='lyric',
            old_name='Song',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Artiste',
            new_name='artiste',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Date_released',
            new_name='date_released',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Vote',
            new_name='vote',
        ),
        migrations.AlterField(
            model_name='artiste',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
